# Project: exp1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = job1.o
LINKOBJ  = job1.o
LIBS     = -L"E:/Programe files/Dev-Cpp/MinGW64/lib" -L"E:/Programe files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Programe files/Dev-Cpp/MinGW64/include" -I"E:/Programe files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programe files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/workspace/C++/eigen-eigen-b30b87236a1b"
CXXINCS  = -I"E:/Programe files/Dev-Cpp/MinGW64/include" -I"E:/Programe files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programe files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Programe files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"E:/workspace/C++/eigen-eigen-b30b87236a1b"
BIN      = exp1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

job1.o: job1.cpp
	$(CPP) -c job1.cpp -o job1.o $(CXXFLAGS)
